server:
  port: 8080
spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 502746126452-vsaer38asm1lhst33d2bsn1sg72c1kfk.apps.googleusercontent.com
            client-secret: gKra8Wji3cCSQdMolhQOULbU
            scope:
            - email
            - profile            
  mail:
    host: smtp.gmail.com
    password: bbmnmzfsizielpym
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: nguyenvothanhhuy2002@gmail.com
            